require "user.options"
require "user.plugins"
require "user.keymaps"
require "user.autocmd"
require "user.colorscheme"
require "user.toggleterm"
require "user.treesitter"
-- require "user.fidget"
require "user.lspzero"
require "user.colorizer"
require "user.comment"
require "user.comp"
require "user.lualine"
require "user.whichkey"
-- require "user.neorg"
require "user.bufferline"
require "user.telescp"
require "user.nvim-tree"
require "user.noice"
-- require "user.sg"

